kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: "getstartedjava-{{ .Values.UserName }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "getstartedjava-{{ .Values.UserName }}"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: "getstartedjava-{{ .Values.UserName }}"
        image: "de.icr.io/cr-namespace-{{ .Values.UserName }}/getstartedjava:{{ .Values.getstartedtag }}"
        env:
          - name: VERSION
            value: "1"
          - name: CLOUDANT_URL
            value: "http://cloudant-service-{{ .Values.UserName }}:80"
          - name: dbUsername
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbUsername
          - name: dbPassword
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbPassword
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: "getstartedjava-{{ .Values.UserName }}"
spec:
  selector:
    app: "getstartedjava-{{ .Values.UserName }}"
  type: nodePort
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: http
    nodePort: "{{ .Values.nodePort }}"
